#if defined _dbx_menus_included
 #endinput
#endif
#define _dbx_menus_included

#define COMMUNITYNAME 		"PLAYCORE"

#define UNLOCKABLES_TITLE 	"%s MoneyMod\n  ❖ Unlockables\n "
#define MAINMENU_TITLE 		"%s MoneyMod\n  ❖ Main Menu\n "
#define UPGRADES_TITLE 		"%s MoneyMod\n  ❖ Upgrades\n "
#define CHANCES_TITLE 		"%s MoneyMod\n  ❖ Chances List\n "
#define ACTIVES_TITLE 		"%s MoneyMod\n  ❖ Active Skills List\n "
#define PASSIVES_TITLE 		"%s MoneyMod\n  ❖ Passive Skills List\n "
